blank_issues_enabled: false
contact_links:
  - name: OpenXilEnv Discussions
    url: https://github.com/eclipse-openxilenv/openxilenv/discussions
    about: Ask questions or discuss ideas before filing an issue