name: Run Self Tests

on:
  push:
    branches: [ bugfix/fix-xilenvrpc-for-linux ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  run-self-tests-on-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: openxilenv

      - name: Download artifact from latest Linux build
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: build.yml
          workflow_conclusion: success  # Only download from successful runs
          name: OpenXilEnv-Linux-Qt6_4_2
          path: OpenXilEnv-Linux-Qt6_4_2
          github_token: ${{ secrets.GH_PAT }}
          
      - name: Check shared library dependencies 
        run: |
          cd /home/runner/work/openxilenv/openxilenv/OpenXilEnv-Linux-Qt6_4_2
          ldd /home/runner/work/openxilenv/openxilenv/OpenXilEnv-Linux-Qt6_4_2/libXilEnvRpc.so
          
