name: Run Self Tests

on:
  push:
    branches: [ bugfix/fix-xilenvrpc-for-linux ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  run-self-tests-on-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: openxilenv

      - name: Download artifact from latest Linux build
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: build.yml
          workflow_conclusion: success  # Only download from successful runs
          name: OpenXilEnv-Linux-Qt6_4_2
          path: OpenXilEnv-Linux-Qt6_4_2
          github_token: ${{ secrets.GH_PAT }}
          
      - name: Prepare test environment
        run: |
          echo "Setting up test environment..."
          python -m venv .venv  # Create a virtual environment
          source .venv/bin/activate  # Activate the virtual environment
          python -m pip install --upgrade pip   # Upgrade pip
          python -m pip install setuptools wheel pytest # Install necessary packages
          cd ./openxilenv/Samples/Automation/Python/OpenXilEnv/  # Navigate to the directory containing setup.py
          python ./setup.py bdist_wheel  # Build the wheel file
          WHEEL=$(ls ./dist/*.whl | head -n 1)
          python -m pip install "$WHEEL"

      - name: Run pytest
        run: |
          echo "Running self tests..."
          source .venv/bin/activate
          pytest -v
